# File: openapi.yaml
openapi: 3.0.0
info:
  title: FFive REST API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Say hello
      responses:
        '200':
          description: Successful response
